#
# Module manifest for module 'ADOpsKit'
#
# Generated by: K Shankar R Karanth
# Generated on: 2026-06-27
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ADOpsKit.psm1'

# Version number of this module.
ModuleVersion = '1.5.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '945d97ae-d509-4243-88ba-dbee505dd0b2'

# Author of this module
Author = 'K Shankar R Karanth'

# Company or vendor of this module
CompanyName = 'karanth.ovh'

# Copyright statement for this module
Copyright = '(c) 2026 K Shankar R Karanth. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Active Directory and Entra ID operations toolkit - inventory, health checks, audit reports, and replication topology diagrams. No ADWS dependency for core functions; uses LDAP and repadmin.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Get-AccountLockoutReport'
    'Get-InsecureLDAPBinds'
    'Enable-DCPerformanceBaseline'
    'Get-ADForestHealth'
    'Test-DCPortHealth'
    'Get-ADArchitectureAssessment'
    'Get-ADReplicationTopologyDiagram'
    'Get-GPOInventoryWithSettings'
    'Get-EntraConnectSyncStatus'
    'Register-ADOpsKitScheduledTasks'
    'Test-ADDCDiagHealth'
    'Register-ADDCDiagHealthMonitor'
    'Invoke-ADRealtimeHeartbeat'
    'Get-DCDecommissionReadiness'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell Gallery.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('ActiveDirectory','AD','EntraID','AzureAD','GPO','Replication','HealthCheck','Audit','Inventory','DomainController','LDAP','HTML','Report','repadmin')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Karanth1992/powershell-scripts/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Karanth1992/powershell-scripts'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'v1.5.0 - Security and reliability release. Fixed Get-EntraConnectSyncStatus reading four properties that do not exist on the real ADSync object types, so its sync-error detection never actually worked (always silently reported clean); it now reads the correct schema and correctly surfaces real sync errors. Removed the hidden WinRM/Invoke-Command dependency in Get-ADForestHealth, which failed outright in WinRM-blocked environments despite documentation claiming otherwise. Fixed Get-DCDecommissionReadiness crashing under strict variable checking when a query failed, and silently reporting "OK" on the pre-decommission checklist for checks that had actually failed to run. Added HTML-encoding of AD-sourced values in Get-DCDecommissionReadiness, Get-ADReplicationTopologyDiagram, and Get-ADForestHealth report output (stored-injection risk in reports opened by administrators). Fixed XPath injection in Get-AccountLockoutReport via usernames containing a single quote. Rewrote Enable-DCPerformanceBaseline, whose logman deployment command could not actually execute as intended over WMI and never checked a real exit code. Fixed a leaked credential handle and a non-fatal ACL-hardening failure on a secrets folder in Register-ADDCDiagHealthMonitor. Fixed Register-ADOpsKitScheduledTasks performing a live AD authentication attempt (risking real account lockout) under -WhatIf. Added atomic state-file writes and self-healing on corrupt state to Invoke-ADRealtimeHeartbeat and Test-ADDCDiagHealth, plus per-notification send isolation so one failed alert no longer skips saving state for the run. Added Set-StrictMode -Version Latest and consistent -LiteralPath usage across every script, which surfaced and fixed further latent bugs in Get-GPOInventoryWithSettings and Test-DCPortHealth. Deduplicated a runspace timeout helper that had been copy-pasted between two scripts.'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
